services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=drive-gateway'
      - 'MYSQL_PASSWORD=qwer1234'
      - 'MYSQL_ROOT_PASSWORD=qwer1234'
      - 'MYSQL_USER=user'
    ports:
      - '3390:3306'

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
#    volumes:
#      - ./mosquitto/conf:/mosquitto/config
#      - ./mosquitto/data:/mosquitto/data
#      - ./mosquitto/log:/mosquitto/log
